[font]
size = 18

[font.normal]
family = "IosevkaNerdFontMono"
style = "Regular"

[font.italic]
family = "IosevkaNerdFontMono"
style = "Regular"

[font.bold]
family = "IosevkaNerdFontMono"
style = "Regular"

[font.bold_italic]
family = "IosevkaNerdFontMono"
style = "Italic"
